### ISSUE TITLE
Read-only API issue needs an ibg.xml written in on start

### ISSUE THREAD

**Issue by dvasdekis** [dvasdekis/ib-gateway-docker-lean#8]
IBC has made a decision to not support disabling the read-only API. [See here](https://github.com/IbcAlpha/IBC/issues/10).

Therefore we need to allow users to write in their own ibg file

**Comment by ghost** [comment]
Just to let you know, IBC 3.8.1 has fixed this issue, so you can fix this in your Docker image if you would like to!  Since IBC >= 3.8.1, add the line "ReadOnlyApi=no" to IBController.ini.  I can submit a pull request if you would like, but I wasn't sure how you wanted to handle this, whether with an env var or something?

**Comment by dvasdekis** [comment]
An env var sounds like a great approach! Feel free to open a Pull Req.
Thanks!
